# Generated by Django 2.2.3 on 2019-07-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(default='?', max_length=500, null=True)),
                ('is_usefull', models.BooleanField(default=True)),
                ('date', models.DateTimeField(verbose_name='Datae transaction')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('create_date', models.DateTimeField(verbose_name='Date criation')),
            ],
        ),
    ]
